# =============================================================================
# FitBuddy – Core AI Engine & Backend Logic
# Built with LangChain + OpenAI GPT-4o-mini + LangSmith Tracing
# =============================================================================
# This module acts as the core AI backend for the FitBuddy application.
# It can be imported by UI frameworks (e.g., Streamlit) or run directly in CLI mode.
# =============================================================================

# ─────────────────────────────────────────────────
# STEP 1: Import Required Libraries & Environment Setup
# ─────────────────────────────────────────────────
import os                                            # Provides operating system interactions (reading environment variables)
from dotenv import load_dotenv                       # Parses key-value pairs from a local .env file into os.environ

# Load environment variables at module import time.
# This ensures LANGSMITH_TRACING, LANGSMITH_API_KEY, and OPENAI_API_KEY are available
# before any LangChain components or LLM connections are instantiated.
load_dotenv()

from langchain_openai import ChatOpenAI              # LangChain integration wrapper around OpenAI's Chat Completion API (GPT models)
from langchain_classic.memory import ConversationBufferMemory  # In-memory storage object for keeping raw conversation message lists
from langchain_core.tools import Tool                # Encapsulates Python functions so LangChain LLMs/Agents can invoke them as tools
from langchain_core.prompts import ChatPromptTemplate # Formats system prompts, dynamic memory contexts, and user messages into LLM inputs
from langchain.agents import create_agent            # Factory method to assemble ReAct agents with tool-calling capabilities
from langchain_core.output_parsers import StrOutputParser # Parses raw LLM AIMessage output objects into plain string strings


# ─────────────────────────────────────────────────
# STEP 2: Define Custom Tools (Math & Calorie Calculator)
# ─────────────────────────────────────────────────
def simple_calculator(expression: str) -> str:
    """
    Safely computes arithmetic expressions requested by the user during chat.
    This function is wrapped as a LangChain Tool so the AI model can calculate
    calorie burns, target macro ratios, or workout durations without hallucinations.

    Args:
        expression (str): A mathematical expression string, e.g. '90 * 6' or '450 / 60'.

    Returns:
        str: String result of the math evaluation or a descriptive error message.
    """
    try:
        # Evaluate arithmetic string using Python's built-in evaluator
        # Note: In production, consider restricted evaluation libraries like numexpr or simpleeval.
        return str(eval(expression))
    except Exception:
        return "Invalid math expression."

# Wrap the python function into a standard LangChain Tool container.
# The `name` and `description` are critical: the LLM reads them to decide when to call the tool.
calculator = Tool(
    name="Calculator",                                # Unique tool name recognized by the LLM reasoning loop
    func=simple_calculator,                           # Target Python function executed upon tool trigger
    description="Performs basic arithmetic operations, e.g., '3 * 4 + 2' or calorie calculations." # Natural language usage guide for LLM
)


# ─────────────────────────────────────────────────
# STEP 3: Multi-Session Memory Management System
# ─────────────────────────────────────────────────
# In-memory dictionary mapping session IDs to conversation history lists.
# Dictionary Structure:
#   Key: session_id (str) -> Unique session identifier (e.g. UUID from Streamlit or 'cli_default')
#   Value: list[tuple[user_text, assistant_summary]] -> List of historical conversation turn tuples
_SESSION_MEMORY: dict[str, list[tuple[str, str]]] = {}


def get_session_memory(session_id: str) -> list[tuple[str, str]]:
    """
    Retrieves or initializes the memory list for a given session ID.

    Args:
        session_id (str): Unique session identifier.

    Returns:
        list[tuple[str, str]]: List of past (user_prompt, assistant_reply) turns.
    """
    # dict.setdefault returns the existing list if key present, else creates and returns []
    return _SESSION_MEMORY.setdefault(session_id, [])


def append_memory(session_id: str, *, user_text: str, assistant_summary: str, max_turns: int = 6) -> None:
    """
    Appends a completed conversation turn to a session's sliding memory window.
    Maintains memory efficiency by trimming older turns when count exceeds max_turns.

    Args:
        session_id (str): Unique session identifier.
        user_text (str): The prompt submitted by the user.
        assistant_summary (str): The text response generated by FitBuddy.
        max_turns (int): Maximum allowed turns retained in sliding memory (default: 6 turns).
    """
    mem = get_session_memory(session_id)
    mem.append((user_text, assistant_summary))
    
    # Enforce sliding window capacity constraint (FIFO eviction)
    if len(mem) > max_turns:
        del mem[0 : len(mem) - max_turns]


def memory_context(session_id: str) -> str:
    """
    Formats historical session turns into a clean, human-readable context block
    suitable for injection into the LangChain system prompt.

    Args:
        session_id (str): Unique session identifier.

    Returns:
        str: Multi-line formatted history string (e.g., "Turn 1 user: ... \n Turn 1 assistant: ...")
    """
    mem = get_session_memory(session_id)
    if not mem:
        return ""
    
    lines = []
    # Format up to the last 6 turns into clear role-attributed text lines
    for i, (user_msg, assistant_msg) in enumerate(mem[-6:], start=1):
        lines.append(f"Turn {i} user: {user_msg}")
        lines.append(f"Turn {i} assistant: {assistant_msg}")
    
    return "\n".join(lines)


def format_conversation_history(conversation_history: list[dict[str, str]] | None, max_messages: int = 8) -> str:
    """
    Converts raw UI chat message lists (e.g., Streamlit session_state messages) into formatted prompt history.

    Args:
        conversation_history (list[dict] | None): List of {"role": "user"/"assistant", "content": "..."} dicts.
        max_messages (int): Maximum recent messages to include (default: 8).

    Returns:
        str: Clean string representation of recent UI chat turns.
    """
    if not conversation_history:
        return ""

    lines = []
    # Process only the most recent N messages to respect context length constraints
    for item in conversation_history[-max_messages:]:
        role = str(item.get("role", "")).strip().lower()
        content = str(item.get("content", "")).strip()
        
        # Filter valid roles and non-empty text content
        if role not in {"user", "assistant"} or not content:
            continue
        lines.append(f"{role.capitalize()}: {content}")
        
    return "\n".join(lines)


# ─────────────────────────────────────────────────
# STEP 4: Fully Agentic LLM Setup (ReAct Agent)
# ─────────────────────────────────────────────────
def init_fitbuddy(api_key: str | None = None, base_url: str | None = None):
    """
    Instantiates and returns the OpenAI LLM model, calculator tool,
    and a fully agentic ReAct agent (`create_agent`).

    Args:
        api_key (str | None): Optional explicit OpenAI API key override.
        base_url (str | None): Optional custom API endpoint base URL.

    Returns:
        tuple[ChatOpenAI, Tool, Agent]: (llm instance, calculator tool, agent)
    """
    # Retrieve credentials from arguments or system environment variables
    key = api_key or os.getenv("OPENAI_API_KEY")
    url = base_url or os.getenv("OPENAI_API_BASE")

    # Instantiate OpenAI Chat Model Wrapper
    llm = ChatOpenAI(
        temperature=0.7,                            # 0.7 temperature allows natural, empathetic coaching responses
        model="gpt-4o-mini",                        # GPT-4o-mini provides fast responses at low cost
        api_key=key,                                # Explicitly pass validated API key
        base_url=url or None,                       # Supports optional custom endpoints / proxies
    )

    tools = [calculator]

    # Create ReAct Agent with Tool integration
    system_prompt = (
        "You are FitBuddy, a friendly AI fitness coach. "
        "Remember what the user says about their workouts or goals. "
        "Use the Calculator tool whenever arithmetic, calorie math, or conversions are required. "
        "Give helpful fitness advice in complete responses, ideally 2–3 sentences with practical next steps."
    )
    
    agent = create_agent(
        model=llm,
        tools=tools,
        system_prompt=system_prompt
    )

    return llm, calculator, agent


def chat_with_fitbuddy(
    user_input: str,
    agent,
    session_id: str,
    conversation_history: list[dict[str, str]] | None,
    calculator=None,
    **kwargs
) -> str:
    """
    Pure Agentic execution entry point.
    Sends user messages directly to the ReAct Agent (`create_agent`).
    Traced automatically in LangSmith.

    Args:
        user_input (str): The user's query or message.
        agent: The ReAct Agent instance initialized via init_fitbuddy().
        session_id (str): Unique identifier for maintaining user session state.
        conversation_history (list[dict] | None): UI chat message history.
        calculator (Tool | None): Optional calculator tool instance.

    Returns:
        str: FitBuddy agent's response.
    """
    # Format historical context from both UI state and background session memory
    conversation_ctx = format_conversation_history(conversation_history)
    memory_ctx = memory_context(session_id)

    try:
        # Combine historical contexts into unified background context string
        context_parts = []
        if memory_ctx:
            context_parts.append(f"Session Memory:\n{memory_ctx}")
        if conversation_ctx:
            context_parts.append(f"Recent Chat:\n{conversation_ctx}")
        full_context = "\n\n".join(context_parts)

        # Build message payload for ReAct Agent
        messages = []
        if full_context:
            messages.append({"role": "system", "content": f"Previous conversation:\n{full_context}"})
        messages.append({"role": "user", "content": user_input})

        # Invoke Agent directly
        agent_response = agent.invoke({"messages": messages})
        
        response_text = ""
        if isinstance(agent_response, dict) and "messages" in agent_response:
            last_msg = agent_response["messages"][-1]
            if hasattr(last_msg, "content"):
                response_text = str(last_msg.content)
            elif isinstance(last_msg, dict) and "content" in last_msg:
                response_text = str(last_msg["content"])
            else:
                response_text = str(last_msg)
        elif hasattr(agent_response, "content"):
            response_text = str(agent_response.content)
        else:
            response_text = str(agent_response)

        # Save turn into active session memory
        append_memory(session_id, user_text=user_input, assistant_summary=response_text)
        return response_text

    except Exception as e:
        print(f"DEBUG: Agent execution error: {e}")
        return f"⚠️ API Error: {str(e)}"


# ─────────────────────────────────────────────────
# STEP 5: Stand-Alone Interactive Command-Line Interface (CLI)
# ─────────────────────────────────────────────────
# Fallback buffer memory object for CLI usage
memory = ConversationBufferMemory(
    memory_key="chat_history",
    input_key="user_input",
    return_messages=True
)


def chat_with_agent(user_input=None):
    """
    Helper function to run single-turn interactions from terminal or script calls.

    Args:
        user_input (str | None): User prompt string. If None, prompts via input().

    Returns:
        str: Response string.
    """
    if user_input is None:
        user_input = input("You: ")

    # Initialize agent & chain using default environment settings
    _, calc, agent, chain = init_fitbuddy()
    session_id = "cli_default"
    return chat_with_fitbuddy(user_input, chain, session_id, None, calculator=calc, agent=agent)


def interactive_chat():
    """
    Runs an interactive terminal loop allowing real-time chat with FitBuddy.
    Exit using 'quit', 'exit', or 'q'.
    """
    print("=== FitBuddy AI Fitness Coach (CLI Mode) ===")
    print("Type 'quit', 'exit', or 'q' to end the conversation")
    print("-" * 45)

    while True:
        try:
            # Prompt user for input and strip surrounding whitespace
            user_input = input("\nYou: ").strip()
            
            # Check for exit commands
            if user_input.lower() in ['quit', 'exit', 'q']:
                print("Goodbye! Stay fit! 💪")
                break
                
            if not user_input:
                continue
                
            # Generate and print response
            response = chat_with_agent(user_input)
            print(f"\nFitBuddy: {response}")
            
        except KeyboardInterrupt:
            # Gracefully handle Ctrl+C interruption
            print("\nGoodbye! Stay fit! 💪")
            break
        except Exception as e:
            print(f"\nError encountered: {e}")


# Script entry point: runs interactive CLI chat when script is executed directly
if __name__ == "__main__":
    interactive_chat()
